[2024-05-24T03:36:54.198+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_python_task.execute_teste_py manual__2024-05-24T03:36:52.069352+00:00 [queued]>
[2024-05-24T03:36:54.217+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_python_task.execute_teste_py manual__2024-05-24T03:36:52.069352+00:00 [queued]>
[2024-05-24T03:36:54.218+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-05-24T03:36:54.246+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): execute_teste_py> on 2024-05-24 03:36:52.069352+00:00
[2024-05-24T03:36:54.258+0000] {standard_task_runner.py:57} INFO - Started process 125 to run task
[2024-05-24T03:36:54.266+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'minio_python_task', 'execute_teste_py', 'manual__2024-05-24T03:36:52.069352+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/dag_teste/teste_***.py', '--cfg-path', '/tmp/tmpiayxqund']
[2024-05-24T03:36:54.269+0000] {standard_task_runner.py:85} INFO - Job 51: Subtask execute_teste_py
[2024-05-24T03:36:54.391+0000] {task_command.py:415} INFO - Running <TaskInstance: minio_python_task.execute_teste_py manual__2024-05-24T03:36:52.069352+00:00 [running]> on host 996d4eb998ba
[2024-05-24T03:36:54.552+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_python_task' AIRFLOW_CTX_TASK_ID='execute_teste_py' AIRFLOW_CTX_EXECUTION_DATE='2024-05-24T03:36:52.069352+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-24T03:36:52.069352+00:00'
[2024-05-24T03:36:54.557+0000] {logging_mixin.py:151} INFO - Iniciando instalação do PySpark...
[2024-05-24T03:36:54.558+0000] {logging_mixin.py:151} INFO - Iniciando a instalação do Java a partir do repositório do GitHub...
[2024-05-24T03:36:54.562+0000] {logging_mixin.py:151} INFO - Ocorreu um erro inesperado durante a instalação do Java a partir do repositório do GitHub: [Errno 2] No such file or directory: '/java:/opt/***/java'
[2024-05-24T03:36:54.563+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-05-24T03:36:54.574+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=minio_python_task, task_id=execute_teste_py, execution_date=20240524T033652, start_date=20240524T033654, end_date=20240524T033654
[2024-05-24T03:36:54.608+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-05-24T03:36:54.654+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
