[2024-05-24T03:23:51.404+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_python_task.execute_teste_py manual__2024-05-24T03:23:50.614104+00:00 [queued]>
[2024-05-24T03:23:51.414+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_python_task.execute_teste_py manual__2024-05-24T03:23:50.614104+00:00 [queued]>
[2024-05-24T03:23:51.415+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-05-24T03:23:51.432+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): execute_teste_py> on 2024-05-24 03:23:50.614104+00:00
[2024-05-24T03:23:51.439+0000] {standard_task_runner.py:57} INFO - Started process 1494 to run task
[2024-05-24T03:23:51.443+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'minio_python_task', 'execute_teste_py', 'manual__2024-05-24T03:23:50.614104+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/dag_teste/teste_***.py', '--cfg-path', '/tmp/tmpf3ckhkso']
[2024-05-24T03:23:51.444+0000] {standard_task_runner.py:85} INFO - Job 42: Subtask execute_teste_py
[2024-05-24T03:23:51.524+0000] {task_command.py:415} INFO - Running <TaskInstance: minio_python_task.execute_teste_py manual__2024-05-24T03:23:50.614104+00:00 [running]> on host 7b5dece41aaf
[2024-05-24T03:23:51.701+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_python_task' AIRFLOW_CTX_TASK_ID='execute_teste_py' AIRFLOW_CTX_EXECUTION_DATE='2024-05-24T03:23:50.614104+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-24T03:23:50.614104+00:00'
[2024-05-24T03:23:51.707+0000] {logging_mixin.py:151} INFO - Iniciando instalação do PySpark...
[2024-05-24T03:23:57.125+0000] {logging_mixin.py:151} INFO - PySpark instalado com sucesso!
[2024-05-24T03:23:57.346+0000] {logging_mixin.py:151} INFO - Ocorreu um erro ao tentar iniciar o Spark: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-05-24T03:23:57.347+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-05-24T03:23:57.392+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=minio_python_task, task_id=execute_teste_py, execution_date=20240524T032350, start_date=20240524T032351, end_date=20240524T032357
[2024-05-24T03:23:57.484+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-05-24T03:23:57.504+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
